name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v3

      - name: 🟡 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.6.0
          run_install: false

      - name: 🟢 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - name: ⚙️ Install & Build
        run: |
          pnpm install
          pnpm build

      - name: 🧪 Running tests
        run: pnpm run test

      - name: 🪶 Checking formatting
        run: pnpm run format:check
